// ============================================
// Quiz.js — AI-Generated Quiz Schema
// ============================================
// Quizzes are generated by AI from note content.
//
// KEY FEATURE:
// Students upload notes → AI generates quiz questions
// This demonstrates Applied AI Engineering.
//
// QUIZ STRUCTURE:
// Each quiz has multiple questions.
// Each question has:
// - Question text
// - 4 options
// - Correct answer index
// - Explanation (AI-generated)
//
// This is your "Active Recall" system.
// Scientifically proven to be the most effective study method.
// ============================================

const mongoose = require("mongoose");

// Sub-schema for individual quiz questions
const questionSchema = new mongoose.Schema(
  {
    question: {
      type: String,
      required: true,
    },

    // Array of 4 answer options
    options: [
      {
        type: String,
        required: true,
      },
    ],

    // Index of the correct answer (0-3)
    correctAnswer: {
      type: Number,
      required: true,
      min: 0,
      max: 3,
    },

    // AI-generated explanation of why this answer is correct
    explanation: {
      type: String,
      default: "",
    },

    // Difficulty level
    difficulty: {
      type: String,
      enum: ["easy", "medium", "hard"],
      default: "medium",
    },
  },
  { _id: true }
);

const quizSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: [true, "Quiz title is required"],
      trim: true,
      maxlength: [200, "Title cannot exceed 200 characters"],
    },

    // Which workspace this quiz belongs to
    workspace: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Workspace",
      required: true,
    },

    // Which note was used to generate this quiz (optional)
    sourceNote: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Note",
      default: null,
    },

    // Who created/triggered this quiz
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // Array of questions
    questions: [questionSchema],

    // Was this quiz AI-generated or manually created?
    generatedByAI: {
      type: Boolean,
      default: true,
    },

    // Total number of questions
    totalQuestions: {
      type: Number,
      default: 0,
    },

    // Quiz attempts by users
    attempts: [
      {
        user: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "User",
        },
        correctAnswers: {
          type: Number,
          default: 0,
          min: 0,
        },
        score: {
          type: Number,
          default: 0,
          min: 0,
          max: 100,
        },
        totalQuestions: Number,
        completedAt: {
          type: Date,
          default: Date.now,
        },
      },
    ],
  },
  {
    timestamps: true,
  }
);

// ============================================
// INDEXES — Speed up quiz queries by workspace
// ============================================
quizSchema.index({ workspace: 1 });
quizSchema.index({ createdBy: 1 });
quizSchema.index({ workspace: 1, createdAt: -1 });

const Quiz = mongoose.model("Quiz", quizSchema);

module.exports = Quiz;
